var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< T >", "structfmt_1_1formatter_3_01T_01_4.html", "structfmt_1_1formatter_3_01T_01_4" ]
    ] ],
    [ "magic_enum", null, [
      [ "customize", null, [
        [ "enum_range< taixu::RetCode >", "structmagic__enum_1_1customize_1_1enum__range_3_01taixu_1_1RetCode_01_4.html", null ]
      ] ]
    ] ],
    [ "taixu", "namespacetaixu.html", [
      [ "editor", "namespacetaixu_1_1editor.html", [
        [ "EditorContext", "structtaixu_1_1editor_1_1EditorContext.html", "structtaixu_1_1editor_1_1EditorContext" ],
        [ "FileEntryModel", "structtaixu_1_1editor_1_1FileEntryModel.html", "structtaixu_1_1editor_1_1FileEntryModel" ],
        [ "FileChildrensHierarchyDataNode", "structtaixu_1_1editor_1_1FileChildrensHierarchyDataNode.html", "structtaixu_1_1editor_1_1FileChildrensHierarchyDataNode" ],
        [ "HierarchyDataNode", "structtaixu_1_1editor_1_1HierarchyDataNode.html", "structtaixu_1_1editor_1_1HierarchyDataNode" ],
        [ "ChildrensHierarchyNode", "structtaixu_1_1editor_1_1ChildrensHierarchyNode.html", "structtaixu_1_1editor_1_1ChildrensHierarchyNode" ],
        [ "ChildrensHierarchyDataNode", "structtaixu_1_1editor_1_1ChildrensHierarchyDataNode.html", null ],
        [ "ChildrensSameHierarchyNode", "structtaixu_1_1editor_1_1ChildrensSameHierarchyNode.html", null ],
        [ "ChildrensArrayHierarchyDataNode", "structtaixu_1_1editor_1_1ChildrensArrayHierarchyDataNode.html", "structtaixu_1_1editor_1_1ChildrensArrayHierarchyDataNode" ],
        [ "EditorStyle", "structtaixu_1_1editor_1_1EditorStyle.html", "structtaixu_1_1editor_1_1EditorStyle" ],
        [ "AbstractUIComponent", "classtaixu_1_1editor_1_1AbstractUIComponent.html", "classtaixu_1_1editor_1_1AbstractUIComponent" ],
        [ "ViewModel", "structtaixu_1_1editor_1_1ViewModel.html", "structtaixu_1_1editor_1_1ViewModel" ],
        [ "DetailComponent", "classtaixu_1_1editor_1_1DetailComponent.html", "classtaixu_1_1editor_1_1DetailComponent" ],
        [ "FileComponent", "classtaixu_1_1editor_1_1FileComponent.html", "classtaixu_1_1editor_1_1FileComponent" ],
        [ "MenuComponent", "classtaixu_1_1editor_1_1MenuComponent.html", "classtaixu_1_1editor_1_1MenuComponent" ],
        [ "RenderComponent", "classtaixu_1_1editor_1_1RenderComponent.html", "classtaixu_1_1editor_1_1RenderComponent" ],
        [ "SceneGraphComponent", "classtaixu_1_1editor_1_1SceneGraphComponent.html", "classtaixu_1_1editor_1_1SceneGraphComponent" ],
        [ "UsefulObjectData", "structtaixu_1_1editor_1_1UsefulObjectData.html", "structtaixu_1_1editor_1_1UsefulObjectData" ],
        [ "UsefulObjectComponent", "classtaixu_1_1editor_1_1UsefulObjectComponent.html", "classtaixu_1_1editor_1_1UsefulObjectComponent" ],
        [ "MainWindow", "classtaixu_1_1editor_1_1MainWindow.html", "classtaixu_1_1editor_1_1MainWindow" ]
      ] ],
      [ "Noncopyable", "classtaixu_1_1Noncopyable.html", "classtaixu_1_1Noncopyable" ],
      [ "StructDataNoncopyable", "structtaixu_1_1StructDataNoncopyable.html", "structtaixu_1_1StructDataNoncopyable" ],
      [ "Handler", "structtaixu_1_1Handler.html", "structtaixu_1_1Handler" ],
      [ "Logger", "classtaixu_1_1Logger.html", "classtaixu_1_1Logger" ],
      [ "GameObject", "classtaixu_1_1GameObject.html", "classtaixu_1_1GameObject" ],
      [ "GuidGenerator", "classtaixu_1_1GuidGenerator.html", null ],
      [ "Manifest", "structtaixu_1_1Manifest.html", "structtaixu_1_1Manifest" ],
      [ "MapArray", "classtaixu_1_1MapArray.html", "classtaixu_1_1MapArray" ],
      [ "SharedPtrOnly", "classtaixu_1_1SharedPtrOnly.html", "classtaixu_1_1SharedPtrOnly" ],
      [ "ThreadPool", "classtaixu_1_1ThreadPool.html", "classtaixu_1_1ThreadPool" ],
      [ "TXRuntimeError", "classtaixu_1_1TXRuntimeError.html", "classtaixu_1_1TXRuntimeError" ],
      [ "Color", "classtaixu_1_1Color.html", "classtaixu_1_1Color" ],
      [ "RandomNumberGenerator", "classtaixu_1_1RandomNumberGenerator.html", "classtaixu_1_1RandomNumberGenerator" ],
      [ "IsSpecialization", "structtaixu_1_1IsSpecialization.html", null ],
      [ "IsSpecialization< Ref< Args... >, Ref >", "structtaixu_1_1IsSpecialization_3_01Ref_3_01Args_8_8_8_01_4_00_01Ref_01_4.html", null ],
      [ "IsArray", "structtaixu_1_1IsArray.html", null ],
      [ "IsArray< std::array< T, N > >", "structtaixu_1_1IsArray_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
      [ "EnginePrivate", "structtaixu_1_1EnginePrivate.html", "structtaixu_1_1EnginePrivate" ],
      [ "VkGlfwExtensions", "structtaixu_1_1VkGlfwExtensions.html", "structtaixu_1_1VkGlfwExtensions" ],
      [ "GLFWWindow", "classtaixu_1_1GLFWWindow.html", "classtaixu_1_1GLFWWindow" ],
      [ "Camera", "classtaixu_1_1Camera.html", "classtaixu_1_1Camera" ],
      [ "EulerCamera", "classtaixu_1_1EulerCamera.html", "classtaixu_1_1EulerCamera" ],
      [ "OrbitingCamera", "classtaixu_1_1OrbitingCamera.html", null ],
      [ "TrackingCamera", "classtaixu_1_1TrackingCamera.html", null ],
      [ "CameraComponent", "classtaixu_1_1CameraComponent.html", "classtaixu_1_1CameraComponent" ],
      [ "RenderableComponent", "classtaixu_1_1RenderableComponent.html", "classtaixu_1_1RenderableComponent" ],
      [ "TransformComponent", "classtaixu_1_1TransformComponent.html", "classtaixu_1_1TransformComponent" ],
      [ "IComponentArray", "classtaixu_1_1IComponentArray.html", "classtaixu_1_1IComponentArray" ],
      [ "ComponentArray", "classtaixu_1_1ComponentArray.html", "classtaixu_1_1ComponentArray" ],
      [ "ComponentManager", "classtaixu_1_1ComponentManager.html", "classtaixu_1_1ComponentManager" ],
      [ "EntityManager", "classtaixu_1_1EntityManager.html", "classtaixu_1_1EntityManager" ],
      [ "Event", "classtaixu_1_1Event.html", "classtaixu_1_1Event" ],
      [ "EventManager", "classtaixu_1_1EventManager.html", "classtaixu_1_1EventManager" ],
      [ "ECSCoordinator", "classtaixu_1_1ECSCoordinator.html", "classtaixu_1_1ECSCoordinator" ],
      [ "System", "structtaixu_1_1System.html", "structtaixu_1_1System" ],
      [ "SystemManager", "classtaixu_1_1SystemManager.html", "classtaixu_1_1SystemManager" ],
      [ "CubeRenderable", "classtaixu_1_1CubeRenderable.html", "classtaixu_1_1CubeRenderable" ],
      [ "DirLight", "structtaixu_1_1DirLight.html", "structtaixu_1_1DirLight" ],
      [ "PointLight", "structtaixu_1_1PointLight.html", "structtaixu_1_1PointLight" ],
      [ "SpotLight", "structtaixu_1_1SpotLight.html", "structtaixu_1_1SpotLight" ],
      [ "LightsInfo", "structtaixu_1_1LightsInfo.html", "structtaixu_1_1LightsInfo" ],
      [ "MaterialInfo", "structtaixu_1_1MaterialInfo.html", "structtaixu_1_1MaterialInfo" ],
      [ "Matrices", "structtaixu_1_1Matrices.html", "structtaixu_1_1Matrices" ],
      [ "IRenderStrategy", "classtaixu_1_1IRenderStrategy.html", "classtaixu_1_1IRenderStrategy" ],
      [ "Scene", "classtaixu_1_1Scene.html", "classtaixu_1_1Scene" ],
      [ "TXShaderModuleManager", "classtaixu_1_1TXShaderModuleManager.html", "classtaixu_1_1TXShaderModuleManager" ],
      [ "ImGuiComponentInfo", "structtaixu_1_1ImGuiComponentInfo.html", "structtaixu_1_1ImGuiComponentInfo" ],
      [ "ImguiStyleGroup", "structtaixu_1_1ImguiStyleGroup.html", "structtaixu_1_1ImguiStyleGroup" ],
      [ "TXSceneRenderer", "classtaixu_1_1TXSceneRenderer.html", "classtaixu_1_1TXSceneRenderer" ],
      [ "TXShaderModuleCreateInfo", "structtaixu_1_1TXShaderModuleCreateInfo.html", "structtaixu_1_1TXShaderModuleCreateInfo" ],
      [ "TXShaderModule", "classtaixu_1_1TXShaderModule.html", "classtaixu_1_1TXShaderModule" ],
      [ "InputState", "structtaixu_1_1InputState.html", "structtaixu_1_1InputState" ],
      [ "InputSystem", "classtaixu_1_1InputSystem.html", "classtaixu_1_1InputSystem" ],
      [ "KeyEvent", "structtaixu_1_1KeyEvent.html", "structtaixu_1_1KeyEvent" ],
      [ "BaseRawData", "structtaixu_1_1BaseRawData.html", "structtaixu_1_1BaseRawData" ],
      [ "Image", "structtaixu_1_1Image.html", "structtaixu_1_1Image" ],
      [ "AssetHeader", "structtaixu_1_1AssetHeader.html", "structtaixu_1_1AssetHeader" ],
      [ "Material", "structtaixu_1_1Material.html", "structtaixu_1_1Material" ],
      [ "Mesh", "structtaixu_1_1Mesh.html", "structtaixu_1_1Mesh" ],
      [ "AssetManager", "classtaixu_1_1AssetManager.html", null ]
    ] ],
    [ "AbstractFactory", "classAbstractFactory.html", "classAbstractFactory" ],
    [ "CpuClock", "classCpuClock.html", "classCpuClock" ],
    [ "CreateFunctor", "classCreateFunctor.html", "classCreateFunctor" ],
    [ "CreateSharedPtrFunctor", "classCreateSharedPtrFunctor.html", "classCreateSharedPtrFunctor" ],
    [ "CreateUniquePtrFunctor", "classCreateUniquePtrFunctor.html", "classCreateUniquePtrFunctor" ],
    [ "CreateWrapperFunctor", "classCreateWrapperFunctor.html", "classCreateWrapperFunctor" ],
    [ "DPIScale", "structDPIScale.html", "structDPIScale" ],
    [ "Engine", "classEngine.html", "classEngine" ],
    [ "EngineArgs", "classEngineArgs.html", "classEngineArgs" ],
    [ "NeededQueueResult", "structNeededQueueResult.html", "structNeededQueueResult" ],
    [ "Project", "classProject.html", "classProject" ],
    [ "ProjectRaw", "classProjectRaw.html", "classProjectRaw" ],
    [ "RingBuffer", "classRingBuffer.html", "classRingBuffer" ],
    [ "SwapchainResult", "structSwapchainResult.html", "structSwapchainResult" ],
    [ "TXCommandProxy", "structTXCommandProxy.html", null ],
    [ "TXCommandQueue", "structTXCommandQueue.html", "structTXCommandQueue" ],
    [ "TXGFXContextFactory", "classTXGFXContextFactory.html", null ],
    [ "TXGFXCreateInfo", "structTXGFXCreateInfo.html", "structTXGFXCreateInfo" ],
    [ "TXGFXProxy", "structTXGFXProxy.html", null ],
    [ "TXPipelineCreateInfo", "structTXPipelineCreateInfo.html", "structTXPipelineCreateInfo" ],
    [ "TXPipelineLayout", "classTXPipelineLayout.html", null ],
    [ "TXShaderDescriptor", "structTXShaderDescriptor.html", "structTXShaderDescriptor" ],
    [ "VKAllocator", "classVKAllocator.html", "classVKAllocator" ],
    [ "VKContext", "classVKContext.html", "classVKContext" ],
    [ "VKFramebuffer", "classVKFramebuffer.html", "classVKFramebuffer" ],
    [ "VKImage", "classVKImage.html", "classVKImage" ],
    [ "VKPipeline", "classVKPipeline.html", "classVKPipeline" ],
    [ "VKPipelineLayout", "classVKPipelineLayout.html", "classVKPipelineLayout" ],
    [ "VKRenderPass", "classVKRenderPass.html", "classVKRenderPass" ],
    [ "VKShaderMod", "classVKShaderMod.html", "classVKShaderMod" ],
    [ "VKSwapchain", "classVKSwapchain.html", "classVKSwapchain" ],
    [ "Window", "classWindow.html", "classWindow" ],
    [ "WindowFactory", "classWindowFactory.html", null ],
    [ "WindowInfo", "structWindowInfo.html", "structWindowInfo" ],
    [ "WindowState", "structWindowState.html", "structWindowState" ],
    [ "World", "structWorld.html", "structWorld" ]
];