name: Documentation

on:
  push:
    branches:
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Configure CPM caching
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen graphviz

      - name: Build
        run: |
          cmake -Sdocs -Bbuild
          cmake --build build --target TaixuApiDocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TAIXU_GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html