name: Format and Lint Cpp

on:
  pull_request:
    paths:
      - "engine/**"

jobs:
  format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DoozyX/clang-format-lint-action@v0.16.1
        with:
          source: './engine'
          exclude: './engine/assets ./engine/shaders'
          extensions: 'hpp,cpp,inl'
          clangFormatVersion: 16
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.TAIXU_GITHUB_TOKEN }}

  lint:
    name: Clang Tidy
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Optionally generate compile_commands.json
      - uses: ZedThree/clang-tidy-review@v0.14.0
        id: review

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.14.0
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1